# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAGigwUJZ7TI5rAhr6pckZhYOWz2MZnR
"""

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("Titanic-Dataset.csv")
df.head()

import pandas as pd
from scipy.stats import shapiro,f_oneway

"""# :Оставляем только нужные колонки"""

df=df[['Sex','Survived','Age']]
df.head()

df[df['Age'].isna()]

df=df.dropna(subset=['Age'])

df[df['Age'].isna()]

df.columns=df.columns.str.lower()

male_survived=df[(df['sex']=='male')&(df['survived']==1)]['age']
male_died=df[(df['sex']=='male')&(df['survived']==0)]['age']
female_survived=df[(df['sex']=='female')&(df['survived']==1)]['age']
female_died=df[(df['sex']=='female')&(df['survived']==0)]['age']

groups={
    'Male Survived':male_survived,
    'Male Died':male_died,
    'Female Survived':female_survived,
    'Female Died':female_died
}

"""Критерий шапиро"""

normal=True
for group_name,group_data in groups.items():
  statistic,p_value=shapiro(group_data)
  print(f"{group_name}: p-p_value={p_value=:.4f}")
  if p_value<0.05:
    normal=False
    break
if normal:
  print("Данные распределены нормально")
else:
  print("Данные не распределены нормально")

normal

"""Так как рапределение не норьмальное, мы не можем применять анову"""

